Repository rizinorg/cutter, pull requests merged in 2020-07, with the labels that each got.

#2280 Add links to Telegram and IRC in the issue template
  .github/ISSUE_TEMPLATE/config.yml
Labels: Documentation

#2289 Use fixed meson version. Latest causing problems for r2.
  .appveyor.yml
Labels: Build System

#2290 IDE setup instructions and comparison
  .gitignore
  docs/source/conf.py
  docs/source/developers-docs/ide-setup.rst
Labels: Documentation

#2293 Improve contribution guidelines
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  docs/.gitignore
  docs/cutter_theme/layout.html
  docs/cutter_theme/static/admonitions.css
  docs/cutter_theme/static/cutter.css_t
  docs/cutter_theme/static/cutter.js
  docs/source/conf.py
  docs/source/contributing.rst
  docs/source/contributing/code.rst
  docs/source/contributing/code/crash-handling-system.rst
  docs/source/contributing/code/development-guidelines.rst
  docs/source/contributing/code/getting-started.rst
  docs/source/contributing/code/ide-setup.rst
  docs/source/contributing/docs/getting-started.rst
  docs/source/contributing/plugins/disasm-dynamic.png
  docs/source/contributing/plugins/disasm-static.png
  docs/source/contributing/plugins/getting-started.rst
  docs/source/contributing/plugins/mydockwidget-action.png
  docs/source/contributing/plugins/mydockwidget.png
  docs/source/contributing/plugins/preferences-plugins.png
  docs/source/contributing/translations/getting-started.rst
  docs/source/developers-docs/first-time.rst
  docs/source/index.rst
  docs/source/plugins.rst
  docs/source/user-docs.rst
  docs/source/user-docs/shortcuts.rst
Labels: Documentation

#2303 Reset last seen memory widget during layout switching.
  src/core/MainWindow.cpp
  src/widgets/AddressableDockWidget.cpp
  src/widgets/AddressableDockWidget.h
  src/widgets/CutterDockWidget.cpp
  src/widgets/CutterDockWidget.h
Labels: BUG

#2307 Don't use @a: for listing cpus.
  src/dialogs/InitialOptionsDialog.cpp
  src/dialogs/InitialOptionsDialog.h
Labels: BUG

#2306 add notes to explain the documentation is splited in two : the websit…
  docs/source/contributing/docs/getting-started.rst
Labels: Documentation

#2259 Cutter docs update
  docs/source/building.rst
  docs/source/common-errors.rst
  docs/source/contributing/code/crash-handling-system.rst
  docs/source/contributing/code/development-guidelines.rst
  docs/source/contributing/code/getting-started.rst
  docs/source/contributing/code/ide-setup.rst
  docs/source/contributing/docs/getting-started.rst
  docs/source/contributing/plugins/getting-started.rst
  docs/source/index.rst
  docs/source/user-docs.rst
  docs/source/user-docs/command-line.rst
  docs/source/user-docs/common-issues.rst
  docs/source/user-docs/menus.rst
  docs/source/user-docs/menus/breakpoints-widget-context-menu.rst
  docs/source/user-docs/menus/debug-buttons-toolbar.rst
  docs/source/user-docs/menus/disassembly-context-menu.rst
  docs/source/user-docs/menus/disassembly-context-menu/debug-context-menu.rst
  docs/source/user-docs/menus/disassembly-context-menu/manage-breakpoints-context-menu.rst
  docs/source/user-docs/menus/disassembly-context-menu/patching.rst
  docs/source/user-docs/menus/disassembly-context-menu/set-current-bits.rst
  docs/source/user-docs/menus/disassembly-context-menu/set-immediate-base.rst
  docs/source/user-docs/menus/graph-widget-context-menu.rst
  docs/source/user-docs/menus/hexdump-context-menu/patching.rst
  docs/source/user-docs/menus/information-windows-menu.rst
  docs/source/user-docs/menus/menu-bar.rst
  docs/source/user-docs/menus/menu-bar/debug-menu.rst
  docs/source/user-docs/menus/menu-bar/edit-menu.rst
  docs/source/user-docs/menus/menu-bar/file-menu.rst
  docs/source/user-docs/menus/menu-bar/help-menu.rst
  docs/source/user-docs/menus/menu-bar/plugins-menu.rst
  docs/source/user-docs/menus/menu-bar/view-menu.rst
  docs/source/user-docs/menus/menu-bar/windows-menu.rst
  docs/source/user-docs/menus/set-table-layout.rst
  docs/source/user-docs/menus/stack-widget-context-menu.rst
  docs/source/user-docs/menus/syncing-a-widget.rst
  docs/source/user-docs/preferences/layout.rst
  docs/source/user-docs/shortcuts.rst
Labels: Documentation

#2335 Fix double jquery definition
  docs/cutter_theme/layout.html
Labels: Documentation

#2346 Temporary workaround for brew problems in github actions.
  .github/workflows/ccpp.yml
Labels: CI

#2347 Test if latest appveyor image update broke shibokken
  .appveyor.yml
Labels: CI
