Repository rizinorg/cutter, pull requests merged in 2020-01, with the labels that each got.

#1975 Breakpoint editor dialog
  docs/source/shortcuts.rst
  src/common/Helpers.cpp
  src/common/Helpers.h
  src/core/Cutter.cpp
  src/core/Cutter.h
  src/core/CutterDescriptions.h
  src/dialogs/BreakpointsDialog.cpp
  src/dialogs/BreakpointsDialog.h
  src/dialogs/BreakpointsDialog.ui
  src/menus/DisassemblyContextMenu.cpp
  src/menus/DisassemblyContextMenu.h
  src/widgets/BreakpointWidget.cpp
  src/widgets/BreakpointWidget.h
Labels: Debug

#2029 Context menu extensions
  src/bindings/bindings.xml
  src/core/Cutter.cpp
  src/core/Cutter.h
  src/core/MainWindow.cpp
  src/core/MainWindow.h
  src/menus/AddressableItemContextMenu.cpp
  src/menus/AddressableItemContextMenu.h
  src/menus/DisassemblyContextMenu.cpp
  src/menus/DisassemblyContextMenu.h
Labels: Plugin

#2031 Fix Python version for Coverity GH Action
  .github/workflows/coverity-scan.yml
Labels: Build System
