Repository rizinorg/cutter, pull requests merged in 2021-09, with the labels that each got.

#2736 CI: use Ubuntu 18.04 as oldest supported build system
  .github/workflows/ccpp.yml
Labels: Build System, CI

#2757 Use open API instead of commands
  src/common/AnalTask.cpp
  src/core/Cutter.cpp
  src/core/Cutter.h
Labels: rizin

#2756 Use hash API instead of commands
  src/widgets/HexdumpWidget.cpp
Labels: rizin

#2749 Update jsdec to development state before it is released
  dist/bundle_jsdec.ps1
  scripts/jsdec.sh
Labels: Decompiler
