Repository rizinorg/cutter, pull requests merged in 2025-05, with the labels that each got.

#3475 Minor fixes to python plugin tutorial.
  docs/source/contributing/plugins/getting-started.rst
Labels: Documentation

#3473 Make CutterCore::core API harder to misuse.
  src/common/Configuration.cpp
  src/common/DisassemblyPreview.cpp
  src/common/RizinTask.cpp
  src/core/Cutter.cpp
  src/core/Cutter.h
  src/core/MainWindow.cpp
  src/dialogs/EditVariablesDialog.cpp
  src/dialogs/GlobalVariableDialog.cpp
  src/menus/DecompilerContextMenu.cpp
  src/menus/DisassemblyContextMenu.cpp
  src/widgets/BacktraceWidget.cpp
  src/widgets/CallGraph.cpp
  src/widgets/DebugActions.cpp
  src/widgets/FunctionsWidget.cpp
  src/widgets/TypesWidget.cpp
Labels: Refactoring

#3482 Adjust macos dylib references to keep gatekeeper happy.
  .github/workflows/ci.yml
  cmake/BundledRizin.cmake
  dist/CMakeLists.txt
  dist/MacOSSetupBundle.cmake.in
Labels: macOS

#3480 Improve disassembly arrow position accuracy.
  src/widgets/DisassemblyWidget.cpp
  src/widgets/DisassemblyWidget.h
Labels: BUG, UI

#3478 Missing translation strings
  src/CutterApplication.cpp
  src/common/AnalysisTask.cpp
  src/common/InitialOptions.h
  src/core/Cutter.cpp
  src/core/MainWindow.cpp
  src/core/MainWindow.ui
  src/dialogs/AboutDialog.cpp
  src/dialogs/AsyncTaskDialog.cpp
  src/dialogs/EditMethodDialog.ui
  src/dialogs/InitialOptionsDialog.cpp
  src/dialogs/InitialOptionsDialog.ui
  src/dialogs/NativeDebugDialog.ui
  src/dialogs/RemoteDebugDialog.ui
  src/dialogs/RizinTaskDialog.cpp
  src/dialogs/VersionInfoDialog.cpp
  src/dialogs/VersionInfoDialog.ui
  src/dialogs/XrefsDialog.ui
  src/dialogs/preferences/AnalysisOptionsWidget.cpp
  src/dialogs/preferences/AnalysisOptionsWidget.ui
  src/dialogs/preferences/InitializationFileEditor.cpp
  src/dialogs/preferences/PreferencesDialog.cpp
  src/tools/basefind/BaseFindDialog.ui
  src/tools/basefind/BaseFindResultsDialog.ui
  src/tools/basefind/BaseFindSearchDialog.ui
  src/widgets/BacktraceWidget.ui
  src/widgets/BreakpointWidget.ui
  src/widgets/ColorThemeListView.cpp
  src/widgets/ConsoleWidget.ui
  src/widgets/Dashboard.cpp
  src/widgets/Dashboard.h
  src/widgets/Dashboard.ui
  src/widgets/DecompilerWidget.cpp
  src/widgets/DisassemblerGraphView.cpp
  src/widgets/EntrypointWidget.ui
  src/widgets/FlagsWidget.ui
  src/widgets/FlirtWidget.ui
  src/widgets/GlobalsWidget.ui
  src/widgets/HexdumpWidget.ui
  src/widgets/OverviewWidget.cpp
  src/widgets/ProcessesWidget.ui
  src/widgets/RegisterRefsWidget.ui
  src/widgets/RegistersWidget.ui
  src/widgets/RizinGraphWidget.ui
  src/widgets/SearchWidget.ui
  src/widgets/SegmentsWidget.cpp
  src/widgets/StackWidget.ui
  src/widgets/StringsWidget.ui
  src/widgets/ThreadsWidget.ui
  src/widgets/TypesWidget.ui
  src/widgets/VTablesWidget.cpp
  src/widgets/VTablesWidget.ui
  src/widgets/VisualNavbar.cpp
Labels: Translations

#3433 remember IO mode for recent files
  src/common/Configuration.cpp
  src/common/Configuration.h
  src/common/SettingsUpgrade.cpp
  src/dialogs/NewFileDialog.cpp
Labels: Enhancement, version change
